# Generated by Django 6.0.6 on 2026-06-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patrickprofile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='registedvehicle',
            fields=[
                ('order_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('startdate', models.DateTimeField(auto_now_add=True)),
                ('enddate', models.DateTimeField(blank=True, null=True)),
                ('intialprogress', models.CharField(default='Not Started', max_length=100)),
                ('issue', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
