# Generated by Django 6.0.6 on 2026-06-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrick', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registedvehicle',
            name='order_number',
            field=models.CharField(default='0000000000', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
