# Generated by Django 6.0.6 on 2026-06-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrick', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrickprofile',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
