# Generated by Django 5.0.6 on 2026-06-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrick', '0002_alter_registedvehicle_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='registedvehicle',
            name='equip_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='registedvehicle',
            constraint=models.UniqueConstraint(fields=('department', 'equip_number'), name='unique_equip_per_department'),
        ),
    ]
