# Generated by Django 5.0.6 on 2026-06-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrick', '0003_registedvehicle_equip_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registedvehicle',
            name='equip_id',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
