# Generated by Django 5.0.6 on 2026-07-01 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrick', '0004_registedvehicle_equip_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registedvehicle',
            name='payment',
            field=models.CharField(default='unpaid', max_length=100),
        ),
    ]
