# Generated by Django 5.0.6 on 2026-07-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrick', '0006_alter_registedvehicle_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registedvehicle',
            name='payment',
            field=models.CharField(default='not stated', max_length=100),
        ),
    ]
